name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: make init

      - name: PHPStan
        run: make phpstan

      - name: Psalm
        run: make psalm

      - name: CS check
        run: make cs-check

      - name: Peck
        run: make peck

      - name: Security check
        run: make security-check

      - name: Tests
        run: make test
